// Liste de démarrage, reprise de la liste existante (Liste_menage.pdf).
// Modifiable ensuite directement dans l'application (onglet Bibliothèque).
// Chaque pièce garde son ordre ; chaque tâche son ordre dans la pièce.

module.exports = [
  {
    room: "Général / Toutes les pièces",
    actions: [
      "Aérer les pièces",
      "Vider les poubelles et remplacer les sacs",
      "Épousseter meubles et surfaces",
      "Épousseter cadres, étagères et bibelots",
      "Nettoyer interrupteurs et poignées de porte",
      "Enlever les toiles d'araignée (plafonds, coins)",
      "Nettoyer miroirs et vitres intérieures",
      "Passer l'aspirateur (tapis et sols durs)",
      "Laver les sols à la serpillière",
      "Nettoyer plinthes",
      "Nettoyer portes et chambranles",
      "Désinfecter télécommandes, téléphones, claviers",
      "Vider et nettoyer corbeilles à papier",
    ],
  },
  {
    room: "Cuisine",
    actions: [
      "Vider et nettoyer évier (robinet inclus)",
      "Nettoyer plan de travail",
      "Nettoyer plaque de cuisson",
      "Nettoyer hotte (extérieur)",
      "Nettoyer hotte (filtre)",
      "Nettoyer four (intérieur)",
      "Nettoyer four (extérieur)",
      "Nettoyer micro-ondes (intérieur et extérieur)",
      "Nettoyer extérieur du frigo",
      "Nettoyer intérieur du frigo",
      "Nettoyer extérieur lave-vaisselle",
      "Lancer / vider le lave-vaisselle",
      "Faire la vaisselle à la main",
      "Nettoyer façades de meubles et placards",
      "Dégraisser crédence / carrelage mural",
      "Nettoyer petit électroménager (cafetière, grille-pain)",
      "Sortir et nettoyer poubelle de cuisine",
      "Balayer et laver le sol",
      "Changer torchons et éponges",
    ],
  },
  {
    room: "Salon / Séjour",
    actions: [
      "Épousseter table basse et meubles TV",
      "Nettoyer écran TV",
      "Aspirer canapé et fauteuils",
      "Aspirer sous les coussins",
      "Secouer / aérer coussins et plaids",
      "Plier plaids et ranger coussins",
      "Aspirer tapis",
      "Nettoyer vitres et baies vitrées",
      "Arroser les plantes",
      "Épousseter feuilles des plantes",
      "Ranger livres, magazines, télécommandes",
    ],
  },
  {
    room: "Salle à manger",
    actions: [
      "Nettoyer table",
      "Nettoyer chaises (assises et dossiers)",
      "Épousseter buffet / vaisselier",
      "Nettoyer suspension / luminaire",
      "Aspirer et laver le sol",
    ],
  },
  {
    room: "Chambres (par chambre)",
    actions: [
      "Faire le lit / changer les draps",
      "Aérer matelas (retourner si demandé)",
      "Épousseter table de chevet et lampes",
      "Épousseter commode et coiffeuse",
      "Vider corbeille",
      "Ranger vêtements qui traînent",
      "Aspirer (sous le lit inclus)",
      "Laver le sol",
      "Nettoyer miroir",
      "Nettoyer fenêtre intérieure",
    ],
  },
  {
    room: "Salles de bain (par SdB)",
    actions: [
      "Nettoyer et désinfecter lavabo et robinetterie",
      "Nettoyer miroir",
      "Nettoyer plan de toilette",
      "Détartrer douche / paroi de douche",
      "Détartrer baignoire",
      "Nettoyer et désinfecter WC (intérieur, extérieur, abattant)",
      "Nettoyer brosse WC et support",
      "Laver le carrelage mural (douche)",
      "Vider poubelle et changer le sac",
      "Changer serviettes et tapis",
      "Remplir savon, papier toilette, mouchoirs",
      "Balayer et laver le sol",
      "Nettoyer interrupteurs et prise rasoir",
    ],
  },
  {
    room: "Bureau",
    actions: [
      "Épousseter bureau et étagères",
      "Nettoyer écran et clavier",
      "Ranger papiers visibles",
      "Vider corbeille papier",
      "Aspirer et laver le sol",
    ],
  },
  {
    room: "Buanderie / Lingerie",
    actions: [
      "Lancer une machine de linge",
      "Étendre / mettre au sèche-linge",
      "Plier le linge propre",
      "Repasser (préciser quelles pièces)",
      "Ranger le linge dans les armoires",
      "Nettoyer extérieur lave-linge et sèche-linge",
      "Nettoyer filtre du sèche-linge",
      "Laver le sol",
    ],
  },
  {
    room: "Entrée / Hall / Escaliers / Couloirs",
    actions: [
      "Ranger chaussures et manteaux",
      "Épousseter console et meuble d'entrée",
      "Nettoyer miroir d'entrée",
      "Secouer / nettoyer paillasson",
      "Aspirer escaliers (marches et contremarches)",
      "Laver rampe d'escalier",
      "Aspirer couloirs",
      "Laver le sol des couloirs",
    ],
  },
  {
    room: "Extérieur / Terrasse / Balcon",
    actions: [
      "Balayer terrasse / balcon",
      "Nettoyer mobilier de jardin",
      "Sortir poubelles au point de collecte",
      "Nettoyer entrée extérieure / paillasson",
      "Arroser plantes extérieures",
    ],
  },
  {
    room: "Tâches occasionnelles / Périodiques",
    actions: [
      "Laver vitres extérieures",
      "Laver rideaux / voilages",
      "Aspirer matelas",
      "Retourner matelas",
      "Nettoyer en profondeur intérieur du frigo",
      "Dégivrer / nettoyer congélateur",
      "Détartrer cafetière / bouilloire",
      "Nettoyer placards (intérieur)",
      "Nettoyer radiateurs",
      "Laver housses de coussins",
      "Nettoyer luminaires et abat-jours",
      "Cirer / huiler meubles en bois",
      "Nettoyer bouches d'aération / VMC",
      "Nettoyer poignées et serrures",
    ],
  },
];
